#!/usr/bin/perl
require "max";
use strict;
use warnings;
use 5.010;

my @keys;
foreach (sort keys %ENV) {
    push @keys, length($_);
}
my $len = &max(@keys);
my $format = "%$len"."s => %s\n";
foreach my $key (sort keys %ENV){
    printf $format, $key, $ENV{$key};
}
